--------------------------------------------------------------
 --  Copyright (c) 2012-2026 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/05-work/demo_code/0_git/demo_dsp_proj/fpga_proj_v3/al_ip/XINTF_RAM_DSP_WR_0/XINTF_RAM_DSP_WR_0.vhd
 -- Date	:	2026 08 17
 -- TD version	:	Release_2026.1_SP2
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY XINTF_RAM_DSP_WR_0 IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(8 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(8 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END XINTF_RAM_DSP_WR_0;

ARCHITECTURE struct OF XINTF_RAM_DSP_WR_0 IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 32,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_A	=> 9,
			ADDR_WIDTH_B	=> 9,
			DATA_DEPTH_A	=> 512,
			DATA_DEPTH_B	=> 512,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			IMPLEMENT	=> "20K",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			web	=> '0',
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			ecc_sbiterrinj	=> OPEN,
			ecc_dbiterrinj	=> OPEN,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
