--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/05-work/02_yuanbiao/01_FPGAProject/03_test/03_adc_version3_1_test_newversion_xinzeng/al_ip/ram_samp_data.vhd
 -- Date	:	2025 11 11
 -- TD version	:	5.6.56362
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_v2_macro;
	USE ph1_v2_macro.PH1_COMPONENTS.all;

ENTITY ram_samp_data IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	clkb	: IN STD_LOGIC
	);
END ram_samp_data;

ARCHITECTURE struct OF ram_samp_data IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 16,
			DATA_WIDTH_B	=> 16,
			ADDR_WIDTH_A	=> 14,
			ADDR_WIDTH_B	=> 14,
			DATA_DEPTH_A	=> 16383,
			DATA_DEPTH_B	=> 16383,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			IMPLEMENT	=> "20K",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "0000000000000000"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> '1',
			ceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			web	=> '0',
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			ecc_sbiterrinj	=> OPEN,
			ecc_dbiterrinj	=> OPEN,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
