--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/05-work/demo_code/test_xintf/fpga_proj_v3/al_ip/reg_ram_ip.vhd
 -- Date	:	2025 12 17
 -- TD version	:	5.6.56362
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_v2_macro;
	USE ph1_v2_macro.PH1_COMPONENTS.all;

ENTITY reg_ram_ip IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	rsta	: IN STD_LOGIC;

	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	web	: IN STD_LOGIC;
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END reg_ram_ip;

ARCHITECTURE struct OF reg_ram_ip IS

	BEGIN

	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 32,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_A	=> 10,
			ADDR_WIDTH_b	=> 10,
			DATA_DEPTH_A	=> 1024,
			DATA_DEPTH_B	=> 1024,
			MODE		=> "DP",
			REGMODE_A	=> "OUTREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			IMPLEMENT	=> "20K",
			INIT_FILE		=> "NONE",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			FILL_ALL		=> "00000000000000000000000000000000"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			ocea	=> '1',
			oceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> rsta,
			rstb	=> rstb,
			doa	=> doa,
			dob	=> dob
		);

END struct;
